Implemented new flow style

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -203,35 +203,27 @@ cmd_start() {
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git fetch -q "$ORIGIN"
-        git checkout "$DEVELOP_BRANCH"
-        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" || die "could not ff $DEVELOP_BRANCH"
+        echo -n "[+] Fetching $ORIGIN... "
+    		git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "could not fetch $ORIGIN"
+        echo "OK"
+        echo -n "[+] Checking out $DEVELOP_BRANCH... "
+        git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1
+        echo "OK"
+        echo -n "[+] Fast-forward $DEVELOP_BRANCH to $ORIGIN/$DEVELOP_BRANCH... "
+        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "could not ff $DEVELOP_BRANCH"
+        echo "OK"
 	fi
     require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
-	# create branch
-	if ! git checkout -b "$BRANCH" "$BASE"; then
-		die "Could not create feature branch '$BRANCH'"
-	fi
+  echo -n "[+] Cretaing branch $BRANCH starting at $BASE... "
+	git checkout -b "$BRANCH" "$BASE" >> $LOGFILE 2>&1 || die "Could not create feature branch '$BRANCH'"
+  echo "OK"
 
-    git submodule init
-    git submodule update
+    echo -n "[+] Updating submodules... "
+    git submodule init || die "Failed to init submodules" >> $LOGFILE 2>&1
+    git submodule update || die "Failed to update submodules" >> $LOGFILE 2>&1
+    echo "OK"
 
-	echo
-	echo "Summary of actions:"
-    if flag fetch; then
-        echo "- Updates were fetched form remote repo before starting"
-    else
-        echo "- Updates were NOT fetched from remote repo. Your may have merge problems afterwards"
-    fi
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
-	echo "- Submodules were inited and updated"
-	echo "- You are now on branch '$BRANCH'"
-	echo ""
-	echo "Now, start committing on your feature. When done, use:"
-	echo ""
-	echo "     git flow feature finish $NAME"
-	echo
 }
 
 cmd_finish() {
@@ -290,9 +282,15 @@ cmd_finish() {
 
 	# update local repo with remote changes first, if asked
     if flag fetch; then
-        git fetch -q "$ORIGIN"
-        git checkout "$DEVELOP_BRANCH"
-        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH"
+        echo -n "[+] Fetching $ORIGIN... "
+        git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "Unable to fetch $ORIGIN"
+        echo "OK"
+        echo -n "[+] Checking out $DEVELOP_BRANCH... "
+        git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $DEVELOP_BRANCH."
+        echo "OK"
+        echo -n "[+] Fast-forward $DEVELOP_BRANCH to $ORIGIN/$DEVELOP_BRANCH... "
+        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Unable to ff $DEVELOP_BRANCH"
+        echo "OK"
     fi
 
 	if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
@@ -311,29 +309,31 @@ cmd_finish() {
 		fi
 	fi
 
-	# merge into BASE
-	git checkout "$DEVELOP_BRANCH"
-	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-		git merge --ff "$BRANCH"
-	else
-		git merge --no-ff "$BRANCH"
-	fi
+    if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+      	# merge into BASE
+        echo -n "[+] Checking out $DEVELOP_BRANCH... "
+      	git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $DEVELOP_BRANCH."
+        echo "OK"
+        echo -n "[+] Merging $BRANCH into $DEVELOP_BRANCH... "
+        git merge --no-ff --log "$BRANCH" -m "[FEATURE $NAME] -> $DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "There were merge conflicts." 
+        echo "OK"
+      	if [ $? -ne 0 ]; then
+      		# oops.. we have a merge conflict!
+      		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
+      		mkdir -p "$DOT_GIT_DIR/.gitflow"
+      		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+      		echo
+      		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
+      		echo "    git mergetool"
+      		echo "    git commit"
+      		echo 
+      		echo "You can then complete the finish by running it again:"
+      		echo "    git flow feature finish $NAME"
+      		echo
+      		exit 1
+      	fi
+    fi
 
-	if [ $? -ne 0 ]; then
-		# oops.. we have a merge conflict!
-		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
-		mkdir -p "$DOT_GIT_DIR/.gitflow"
-		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
-		echo
-		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
-		echo "    git mergetool"
-		echo "    git commit"
-		echo 
-		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
-		echo
-		exit 1
-	fi
 
 	# when no merge conflict is detected, just clean up the feature branch
 	helper_finish_cleanup
@@ -346,36 +346,25 @@ helper_finish_cleanup() {
 
 	# delete branch
 	if flag fetch; then
-		git push "$ORIGIN" ":refs/heads/$BRANCH"
+    echo -n "[+] Deleting $BRANCH at $ORIGIN... "
+		git push "$ORIGIN" ":refs/heads/$BRANCH" >> $LOGFILE 2>&1 || die "Unable to delete $BRANCH at $ORIGIN"
+    echo "OK"
 	fi
 	
 	
 	if noflag keep; then
-		git branch -d "$BRANCH"
+    echo -n "[+] Deleting $BRANCH... "
+		git branch -d "$BRANCH" >> $LOGFILE 2>&1 || die "Unable to delete $BRANCH"
+    echo "OK"
 	fi
 
     # upload to remote repo
     if flag upload; then
-        git push "$ORIGIN" "$DEVELOP_BRANCH:$DEVELOP_BRANCH"
-        echo git push "$ORIGIN" "$DEVELOP_BRANCH:$DEVELOP_BRANCH"
+        echo -n "[+] Pushing $DEVELOP_BRANCH to $ORIGIN... "
+        git push "$ORIGIN" "$DEVELOP_BRANCH:$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Unable to push $DEVELOP_BRANCH"
+        echo "OK"
     fi
 
-	echo
-	echo "Summary of actions:"
-	echo "- The feature branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
-	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
-	if flag keep; then
-		echo "- Feature branch '$BRANCH' is still available"
-	else
-		echo "- Feature branch '$BRANCH' has been removed"
-	fi
-    if flag upload; then
-        echo "- Changes to master have been uploaded to remote repository."
-    else
-        echo "- All changes were perfomed locally. Remember to upload to the remote repository manually."
-    fi
-	echo "- You are now on branch '$DEVELOP_BRANCH'"
-	echo
 }
 
 cmd_publish() {
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -165,34 +165,28 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$PRODUCTION_BRANCH"
+        echo -n "[+] Fetching $ORIGIN... "
+		    git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "Unable to fetch $ORIGIN"
+        echo "OK"
+        echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+        git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Unable to fetch $PRODUCTION_BRANCH"
+        echo "OK"
+        echo -n "[+] Fast-forward $PRODUCTION_BRANCH to $ORIGIN/$PRODUCTION_BRANCH... "
+        git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "could not ff $PRODUCTION_BRANCH"
+        echo "OK"
 	fi
-	if has "$ORIGIN/$PRODUCTION_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
-	fi
+    require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 
 	# create branch
-	git checkout -b "$BRANCH" "$BASE"
+  echo -n "[+] Cretaing branch $BRANCH starting at $BASE... "
+	git checkout -b "$BRANCH" "$BASE" >> $LOGFILE 2>&1
+  echo "OK"
 
-    git submodule init
-    git submodule update
+    echo -n "[+] Updating submodules... "
+    git submodule init >> $LOGFILE 2>&1 || die "Failed to init submodules"
+    git submodule update >> $LOGFILE 2>&1 || die "Failed to update submodules"
+    echo "OK"
 
-	echo
-	echo "Summary of actions:"
-    if flag fetch; then
-        echo "- Latest changes where pulled from remote repo before starting."
-    fi
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
-	echo "- Submodules were inited and updated."
-	echo "- You are now on branch '$BRANCH'"
-	echo
-	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
-	echo "- Start committing your hot fixes"
-	echo "- When done, run:"
-	echo
-	echo "     git flow hotfix finish '$VERSION'"
-	echo
 }
 
 cmd_finish() {
@@ -215,42 +209,58 @@ cmd_finish() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$PRODUCTION_BRANCH" || \
-		  die "Could not fetch $PRODUCTION_BRANCH from $ORIGIN."
-        git checkout "$PRODUCTION_BRANCH"
-        git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH" || \
-          die "Could not fast-forward $PRODUCTION_BRANCH"
-
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
-        git checkout "$DEVELOP_BRANCH"
-        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" || \
-          die "Could not fast-forwald $DEVELOP_BRANCH"
+      echo -n "[+] Fetching $ORIGIN... "
+		  git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "Could not fetch $PRODUCTION_BRANCH from $ORIGIN."
+      echo "OK"
+      echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+      git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Unable to checkout $PRODUCTION_BRANCH"
+      echo "OK"
+      echo -n "[+] Fast-forward $PRODUCTION_BRANCH to $ORIGIN/$PRODUCTION_BRANCH... "
+      git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not fast-forward $PRODUCTION_BRANCH"
+      echo "OK"
+      echo -n "[+] Checking out $DEVELOP_BRANCH... "
+      git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Unable to checkout $DEVELOP_BRANCH"
+      echo "OK"
+      echo -n "[+] Fast-forward $DEVELOP_BRANCH to $ORIGIN/$DEVELOP_BRANCH... "
+      git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not fast-forwald $DEVELOP_BRANCH"
+      echo "OK"
 	fi
+
+  if ! git_is_branch_merged_into "$PRODUCTION_BRANCH" "$BRANCH"; then
+      echo "Cannot finish. $PRODUCTION_BRANCH is not an ancestor of $BRANCH."
+      echo "This probably means a HOTFIX or RELEASE was finished after you started $BRANCH."  
+      echo "1) Run 'git merge $PRODUCTION_BRANCH'"
+      echo "2) Test everything again (production will end up different than what you have tested)."
+      echo "3) Run finish command again"
+      git checkout $BRANCH >> $LOGFILE 2>&1
+      exit 1
+  fi
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into master was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$PRODUCTION_BRANCH"; then
-		git checkout "$PRODUCTION_BRANCH" || \
-		  die "Could not check out $PRODUCTION_BRANCH."
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+      echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+		  git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $PRODUCTION_BRANCH."
+      echo "OK"
+      echo -n "[+] Merging $BRANCH into $PRODUCTION_BRANCH... "
+      git merge --no-ff --log "$BRANCH" -m "[HOTFIX $VERSION] -> $PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "There were merge conflicts."
+      echo "OK"
 	fi
 
 	if noflag notag; then
 		# try to tag the release
 		# in case a previous attempt to finish this release branch has failed,
 		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
+		local tagname=v`date -u "+%Y.%m.%d_%H.%M"`"_$BRANCH"
 		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
+			local opts=""
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			git tag $opts "$VERSION_PREFIX$VERSION" || \
-			die "Tagging failed. Please run finish again to retry."
+      echo -n "[+] Tagging $tagname... "
+			git tag $opts "$tagname" >> $LOGFILE 2>&1 || die "Tagging failed. Please run finish again to retry."
+      echo "OK"
 		fi
 	fi
 
@@ -258,47 +268,36 @@ cmd_finish() {
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into develop was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
-
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+    echo -n "[+] Checking out $DEVELOP_BRANCH... "
+		git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $DEVELOP_BRANCH."
+    echo "OK"
+    echo -n "[+] Merging $BRANCH into $DEVELOP_BRANCH... "
+		git merge --no-ff --log "$BRANCH" -m "[HOTFIX $VERSION] -> $DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "There were merge conflicts."
+    echo "OK"
 	fi
 
 	# delete branch
 	if noflag keep; then
-		git branch -d "$BRANCH"
+    if [ "$BRANCH" = "$(git_current_branch)" ]; then
+      git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1
+    fi
+    echo -n "[+] Deleting $BRANCH... "
+		git branch -d "$BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
 	fi
 
 	if flag push; then
-		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git push "$ORIGIN" "$PRODUCTION_BRANCH" || \
-			die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
+    echo -n "[+] Pushing $DEVELOP_BRANCH to $ORIGIN... "
+		git push "$ORIGIN" "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+    echo "OK"
+    echo -n "[+] Pushing $PRODUCTION_BRANCH to $ORIGIN... "
+		git push "$ORIGIN" "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
+    echo "OK"
 		if noflag notag; then
-			git push --tags "$ORIGIN" || \
-				die "Could not push tags to $ORIGIN."
+      echo -n "[+] Pushing tog $VERSION_PREFIX$VERSION to $ORIGIN... "
+			git push "$ORIGIN" "$VERSION_PREFIX$VERSION" >> $LOGFILE 2>&1 || die "Could not push tags to $ORIGIN."
+      echo "OK"
 		fi
 	fi
 
-	echo
-	echo "Summary of actions:"
-	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Hotfix branch has been merged into '$PRODUCTION_BRANCH'"
-	if noflag notag; then
-		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
-	fi
-	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
-	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
-	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
-	fi
-	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$PRODUCTION_BRANCH' and tags have been pushed to '$ORIGIN'"
-	fi
-	echo
 }
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -162,37 +162,38 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$RELEASES_PREFIX$REL_NAME"
 	if flag fetch; then
-		git fetch -q "$ORIGIN"
+        echo -n "[+] Fetching $ORIGIN... "
+        git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "Could not fetch $PRODUCTION_BRANCH from $ORIGIN."
+        echo "OK"
+        echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+        git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Unable to checkout $PRODUCTION_BRANCH"
+        echo "OK"
+        echo -n "[+] Fast-forward $PRODUCTION_BRANCH to $ORIGIN/$PRODUCTION_BRANCH... "
+        git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not fast-forward $PRODUCTION_BRANCH"
+        echo "OK"
+        echo -n "[+] Checking out $DEVELOP_BRANCH... "
+        git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Unable to checkout $DEVELOP_BRANCH"
+        echo "OK"
+        echo -n "[+] Fast-forward $DEVELOP_BRANCH to $ORIGIN/$DEVELOP_BRANCH... "
+        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not fast-forwald $DEVELOP_BRANCH"
+        echo "OK"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+    require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+    require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 
-	# create branch
-	git checkout -b "$BRANCH" "$BASE"
+  echo -n "[+] Creating branch $BRANCH starting at $BASE... "
+	git checkout -b "$BRANCH" "$BASE" >> $LOGFILE 2>&1 || die "Could not create feature branch '$BRANCH'"
+  echo "OK"
+  
+  echo -n "[+] Merging $PRODUCTION_BRANCH into $BRANCH to enable a cleaner finish... "
+	git merge --no-ff "$PRODUCTION_BRANCH" -m "Preparing $BRANCH by merging $PRODUCTION_BRANCH into it" >> $LOGFILE 2>&1 || die "There were merge conflicts."
+  echo "OK"
 
-    git submodule init
-    git submodule update
+    echo -n "[+] Updating submodules... "
+    git submodule init >> $LOGFILE 2>&1
+    git submodule update >> $LOGFILE 2>&1
+    echo "OK"
 
-	echo
-	echo "Summary of actions:"
-    if flag fetch; then
-        echo "- Updates were fetched from remote repo before starting."
-    fi
-    if flag fetch; then
-        echo "- Changes were fetched from the remote repo"
-    fi
-	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
-	echo "- Submodules were inited and updated."
-	echo "- You are now on branch '$BRANCH'"
-	echo
-	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
-	echo "- Start committing last-minute fixes in preparing your release"
-	echo "- When done, run:"
-	echo
-	echo "     git flow release finish '$REL_NAME'"
-	echo
 }
 
 cmd_finish() {
@@ -216,41 +217,62 @@ cmd_finish() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag fetch; then
-		git fetch -q "$ORIGIN" || \
-		  die "Could not fetch from $ORIGIN."
-        git checkout "$PRODUCTION_BRANCH"
-        git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH"
-        git checkout "$DEVELOP_BRANCH"
-        git merge --ff-only "ORIGIN/$DEVELOP_BRANCH"
+    echo -n "[+] Fetching $ORIGIN... "
+		git fetch -q "$ORIGIN" >> $LOGFILE 2>&1 || die "Could not fetch from $ORIGIN."
+    echo "OK"
+    echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+    git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
+    echo -n "[+] Fast-forward $PRODUCTION_BRANCH to $ORIGIN/$PRODUCTION_BRANCH... "
+    git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
+    echo -n "[+] Checking out $DEVELOP_BRANCH... "
+    git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
+    echo -n "[+] Fast-forward $DEVELOP_BRANCH to $ORIGIN/$DEVELOP_BRANCH... "
+    git merge --ff-only "ORIGIN/$DEVELOP_BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
 	fi
+	
     require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
     require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+
+  if ! git_is_branch_merged_into "$PRODUCTION_BRANCH" "$BRANCH"; then
+      echo "Cannot finish. $PRODUCTION_BRANCH is not an ancestor of $BRANCH."
+      echo "This probably means a HOTFIX or RELEASE was finished after you started $BRANCH."
+      echo "1) Run 'git merge $PRODUCTION_BRANCH'"
+      echo "2) Test everything again (production will end up different than what you have tested)."
+      echo "3) Run finish command again"
+      git checkout $BRANCH >> $LOGFILE 2>&1
+      exit 1
+  fi
+
 
 	# try to merge into production
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into production was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$PRODUCTION_BRANCH"; then
-		git checkout "$PRODUCTION_BRANCH" || \
-		  die "Could not check out $PRODUCTION_BRANCH."
-        git merge --ff-only "$ORIGIN"/"$PRODUCTION_BRANCH" || \
-          die "Could not fast forward $PRODUCTION_BRANCH"
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+    echo -n "[+] Checking out $PRODUCTION_BRANCH... "
+		git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $PRODUCTION_BRANCH."
+    echo "OK"
+    echo -n "[+] Merging $BRANCH into $PRODUCTION_BRANCH... "
+ 		git merge --no-ff "$BRANCH" -m "[RELEASE $REL_NAME] -> $PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "There were merge conflicts."
+    echo "OK"
 	fi
 
 	if noflag notag; then
 		# try to tag the release
 		# in case a previous attempt to finish this release branch has failed,
 		# but the tag was set successful, we skip it now
-		local tagname=RELEASES-`date -u "+%Y%h%d-%H%M"`
+		local tagname=v`date -u "+%Y.%m.%d_%H.%M"`"_$BRANCH"
 		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
+			local opts=""
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			git tag $opts "$tagname" || \
-			die "Tagging failed. Please run finish again to retry."
+      echo -n "[+] Tagging $tagname... "
+			git tag $opts "$tagname" >> $LOGFILE 2>&1 || die "Tagging failed. Please run finish again to retry."
+      echo "OK"
 		fi
 	fi
 
@@ -258,59 +280,41 @@ cmd_finish() {
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into develop was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-		git checkout "$DEVELOP_BRANCH" || \
-		  die "Could not check out $DEVELOP_BRANCH."
-        git merge --ff-only "$ORIGIN"/"$DEVELOP_BRANCH" || \
-          die "Could not fast forward $DEVELOP_BRANCH"
-
-		# TODO: Actually, accounting for 'git describe' pays, so we should
-		# ideally git merge --no-ff $tagname here, instead!
-		git merge --no-ff "$BRANCH" || \
-		  die "There were merge conflicts."
-		  # TODO: What do we do now?
+    echo -n "[+] Checking out $DEVELOP_BRANCH... "
+		git checkout "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not check out $DEVELOP_BRANCH."
+    echo "OK"
+    echo -n "[+] Merging $BRANCH into $DEVELOP_BRANCH... "
+		git merge --no-ff "$BRANCH" -m "[RELEASE $REL_NAME] -> $DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "There were merge conflicts."
+    echo "OK"
 	fi
 
 	# delete branch
 	if noflag keep; then
 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git checkout "$PRODUCTION_BRANCH"
+			git checkout "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1
 		fi
-		git branch -d "$BRANCH"
+    echo -n "[+] Deleting $BRANCH... "
+		git branch -d "$BRANCH" >> $LOGFILE 2>&1
+    echo "OK"
 	fi
 
 	if flag push; then
-		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
-			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git push "$ORIGIN" "$PRODUCTION_BRANCH" || \
-			die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
+    echo -n "[+] Pushing $DEVELOP_BRANCH to $ORIGIN... "
+		git push "$ORIGIN" "$DEVELOP_BRANCH" >> $LOGFILE 2>&1 || die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
+    echo "OK"
+    echo -n "[+] Pushing $PRODUCTION_BRANCH to $ORIGIN... "
+		git push "$ORIGIN" "$PRODUCTION_BRANCH" >> $LOGFILE 2>&1 || die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
+    echo "OK"
 		if noflag notag; then
-			git push --tags "$ORIGIN" || \
-			  die "Could not push tags to $ORIGIN."
+      echo -n "[+] Pushing tog $tagname to $ORIGIN... "
+			git push "$ORIGIN" "$tagname" >> $LOGFILE 2>&1 || die "Could not push tags to $ORIGIN."
+      echo "OK"
 		fi
-		git push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
+    echo -n "[+] Deleting $BRANCH at $ORIGIN... "
+		git push "$ORIGIN" ":refs/heads/$BRANCH" >> $LOGFILE 2>&1 || die "Could not delete the remote $BRANCH in $ORIGIN."
+    echo "OK"
 	fi
 
-	echo
-	echo "Summary of actions:"
-    if flag fetch; then
-        echo "- Latest objects have been fetched from '$ORIGIN'"
-    fi
-	echo "- Release branch has been merged into '$PRODUCTION_BRANCH'"
-	if noflag notag; then
-		echo "- The release was tagged '$tagname'"
-	fi
-	echo "- Release branch has been back-merged into '$DEVELOP_BRANCH'"
-	if flag keep; then
-		echo "- Release branch '$BRANCH' is still available"
-	else
-		echo "- Release branch '$BRANCH' has been deleted"
-	fi
-	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$PRODUCTION_BRANCH' and tags have been pushed to '$ORIGIN'"
-		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
-	fi
-	echo
 }
 
 cmd_publish() {
