Changing things...

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -196,19 +196,16 @@ cmd_start() {
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
 	require_name_arg
+	require_clean_working_tree
 
 	# sanity checks
 	require_branch_absent "$BRANCH"
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
-	fi
-
-	# if the origin branch counterpart exists, assert that the local branch
-	# isn't behind it (to avoid unnecessary rebasing)
-	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+		git fetch -q "$ORIGIN"
+        git checkout "DEVELOP_BRANCH"
+        git merge --ff-only "$ORIGIN/$DEVELOP_BRANCH" || die "could not ff $DEVELOP_BRANCH"
 	fi
 
 	# create branch
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -84,8 +84,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-		local master_sha=$(git rev-parse "$MASTER_BRANCH")
+		local base=$(git merge-base "$fullname" "$PRODUCTION_BRANCH")
+		local master_sha=$(git rev-parse "$PRODUCTION_BRANCH")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -139,8 +139,8 @@ require_version_arg() {
 require_base_is_on_master() {
 	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
 			| sed 's/[* ] //g' \
-	  		| grep -q "^$MASTER_BRANCH\$"; then
-		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
+	  		| grep -q "^$PRODUCTION_BRANCH\$"; then
+		die "fatal: Given base '$BASE' is not a valid commit on '$PRODUCTION_BRANCH'."
 	fi
 }
 
@@ -155,7 +155,7 @@ require_no_existing_hotfix_branches() {
 cmd_start() {
 	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
-	BASE=${2:-$MASTER_BRANCH}
+	BASE=${2:-$PRODUCTION_BRANCH}
 	require_version_arg
 	require_base_is_on_master
 	require_no_existing_hotfix_branches
@@ -165,10 +165,10 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$MASTER_BRANCH"
+		git fetch -q "$ORIGIN" "$PRODUCTION_BRANCH"
 	fi
-	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	if has "$ORIGIN/$PRODUCTION_BRANCH" "$(git_remote_branches)"; then
+		require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 	fi
 
 	# create branch
@@ -211,13 +211,13 @@ cmd_finish() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git fetch -q "$ORIGIN" "$PRODUCTION_BRANCH" || \
+		  die "Could not fetch $PRODUCTION_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
 		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
 	fi
-	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	if has "$ORIGIN/$PRODUCTION_BRANCH" "$(git_remote_branches)"; then
+		require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 	fi
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -226,9 +226,9 @@ cmd_finish() {
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
 	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
+	if ! git_is_branch_merged_into "$BRANCH" "$PRODUCTION_BRANCH"; then
+		git checkout "$PRODUCTION_BRANCH" || \
+		  die "Could not check out $PRODUCTION_BRANCH."
 		git merge --no-ff "$BRANCH" || \
 		  die "There were merge conflicts."
 		  # TODO: What do we do now?
@@ -271,8 +271,8 @@ cmd_finish() {
 	if flag push; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$PRODUCTION_BRANCH" || \
+			die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git push --tags "$ORIGIN" || \
 				die "Could not push tags to $ORIGIN."
@@ -282,7 +282,7 @@ cmd_finish() {
 	echo
 	echo "Summary of actions:"
 	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
+	echo "- Hotfix branch has been merged into '$PRODUCTION_BRANCH'"
 	if noflag notag; then
 		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
 	fi
@@ -293,7 +293,7 @@ cmd_finish() {
 		echo "- Hotfix branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$DEVELOP_BRANCH', '$PRODUCTION_BRANCH' and tags have been pushed to '$ORIGIN'"
 	fi
 	echo
 }
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -39,13 +39,13 @@
 require_git_repo
 require_gitflow_initialized
 gitflow_load_settings
-VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
+RELEASES_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
 PREFIX=$(git config --get gitflow.prefix.release)
 
 usage() {
 	echo "usage: git flow release [list] [-v]"
-	echo "       git flow release start [-F] <version>"
-	echo "       git flow release finish [-Fsumpk] <version>"
+	echo "       git flow release start [-F] <release_name>"
+	echo "       git flow release finish [-Fsumpk] <release_name>"
 	echo "       git flow release publish <name>"
 	echo "       git flow release track <name>"
 }
@@ -121,13 +121,13 @@ parse_args() {
 	eval set -- "${FLAGS_ARGV}"
 
 	# read arguments into global variables
-	VERSION=$1
-	BRANCH=$PREFIX$VERSION
+	REL_NAME=$1
+	BRANCH=$PREFIX$REL_NAME
 }
 
-require_version_arg() {
-	if [ "$VERSION" = "" ]; then
-		warn "Missing argument <version>"
+require_release_name_arg() {
+	if [ "$REL_NAME" = "" ]; then
+		warn "Missing argument <release_name>"
 		usage
 		exit 1
 	fi
@@ -153,16 +153,16 @@ cmd_start() {
 	DEFINE_boolean fetch true "fetch from $ORIGIN before performing finish" F
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
-	require_version_arg
+	require_release_name_arg
 	require_base_is_on_develop
 	require_no_existing_release_branches
 
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	require_tag_absent "$VERSION_PREFIX$VERSION"
+	require_tag_absent "$RELEASES_PREFIX$REL_NAME"
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git fetch -q "$ORIGIN"
 	fi
 	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -176,6 +176,9 @@ cmd_start() {
     if flag fetch; then
         echo "- Updates were fetched from remote repo before starting."
     fi
+    if flag fetch; then
+        echo "- Changes were fetched from the remote repo"
+    fi
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
 	echo
@@ -184,7 +187,7 @@ cmd_start() {
 	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
-	echo "     git flow release finish '$VERSION'"
+	echo "     git flow release finish '$REL_NAME'"
 	echo
 }
 
@@ -198,7 +201,7 @@ cmd_finish() {
 	DEFINE_boolean notag false "don't tag this release" n
 
 	parse_args "$@"
-	require_version_arg
+	require_release_name_arg
 
 	# handle flags that imply other flags
 	if [ "$FLAGS_signingkey" != "" ]; then
@@ -209,26 +212,24 @@ cmd_finish() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag fetch; then
-		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-		  die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+		git fetch -q "$ORIGIN" || \
+		  die "Could not fetch from $ORIGIN."
+        git checkout "$PRODUCTION_BRANCH"
+        git merge --ff-only "$ORIGIN/$PRODUCTION_BRANCH"
+        git checkout "$DEVELOP_BRANCH"
+        git merge --ff-only "ORIGIN/$DEVELOP_BRANCH"
 	fi
-	if has "$ORIGIN/$MASTER_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
-	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" "$(git_remote_branches)"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
-	fi
+    require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
+    require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
-	# try to merge into master
+	# try to merge into production
 	# in case a previous attempt to finish this release branch has failed,
-	# but the merge into master was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-		git checkout "$MASTER_BRANCH" || \
-		  die "Could not check out $MASTER_BRANCH."
-        git merge --ff-only "$ORIGIN"/"$MASTER_BRANCH" || \
-          die "Could not fast forward $MASTER_BRANCH"
+	# but the merge into production was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$PRODUCTION_BRANCH"; then
+		git checkout "$PRODUCTION_BRANCH" || \
+		  die "Could not check out $PRODUCTION_BRANCH."
+        git merge --ff-only "$ORIGIN"/"$PRODUCTION_BRANCH" || \
+          die "Could not fast forward $PRODUCTION_BRANCH"
 		git merge --no-ff "$BRANCH" || \
 		  die "There were merge conflicts."
 		  # TODO: What do we do now?
@@ -268,7 +269,7 @@ cmd_finish() {
 	# delete branch
 	if noflag keep; then
 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git checkout "$MASTER_BRANCH"
+			git checkout "$PRODUCTION_BRANCH"
 		fi
 		git branch -d "$BRANCH"
 	fi
@@ -276,8 +277,8 @@ cmd_finish() {
 	if flag push; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-		git push "$ORIGIN" "$MASTER_BRANCH" || \
-			die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		git push "$ORIGIN" "$PRODUCTION_BRANCH" || \
+			die "Could not push to $PRODUCTION_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git push --tags "$ORIGIN" || \
 			  die "Could not push tags to $ORIGIN."
@@ -288,8 +289,10 @@ cmd_finish() {
 
 	echo
 	echo "Summary of actions:"
-	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Release branch has been merged into '$MASTER_BRANCH'"
+    if flag fetch; then
+        echo "- Latest objects have been fetched from '$ORIGIN'"
+    fi
+	echo "- Release branch has been merged into '$PRODUCTION_BRANCH'"
 	if noflag notag; then
 		echo "- The release was tagged '$tagname'"
 	fi
@@ -300,7 +303,7 @@ cmd_finish() {
 		echo "- Release branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		echo "- '$DEVELOP_BRANCH', '$PRODUCTION_BRANCH' and tags have been pushed to '$ORIGIN'"
 		echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
 	fi
 	echo
@@ -308,7 +311,7 @@ cmd_finish() {
 
 cmd_publish() {
 	parse_args "$@"
-	require_version_arg
+	require_release_name_arg
 
 	# sanity checks
 	require_clean_working_tree
@@ -335,7 +338,7 @@ cmd_publish() {
 
 cmd_track() {
 	parse_args "$@"
-	require_version_arg
+	require_release_name_arg
 
 	# sanity checks
 	require_clean_working_tree
