Only first parents when preparing to start/finish changes

diff --git a/git-flow-change b/git-flow-change
--- a/git-flow-change
+++ b/git-flow-change
@@ -158,7 +158,7 @@ cmd_start() {
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
         flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
+        sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
 	fi
     require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 
@@ -191,8 +191,8 @@ cmd_production() {
 	require_clean_working_tree
 	if flag fetch; then
       flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-      sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
-      sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+      sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
+      sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
 
   if ! git_is_branch_merged_into "$PRODUCTION_BRANCH" "$BRANCH"; then
@@ -275,7 +275,7 @@ cmd_master() {
 	require_clean_working_tree
 	if flag fetch; then
       flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-      sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+      sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
 
 	# try to merge into master
diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -206,7 +206,7 @@ cmd_start() {
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
 	    flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+        sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
     require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 
@@ -273,7 +273,7 @@ cmd_finish() {
 	# update local repo with remote changes first, if asked
     if flag fetch; then
     	flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+        sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
     fi
 
 	if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -166,7 +166,7 @@ cmd_start() {
 	require_tag_absent "$VERSION_PREFIX$VERSION"
 	if flag fetch; then
         flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
+        sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
 	fi
     require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
 
@@ -199,8 +199,8 @@ cmd_finish() {
 	require_clean_working_tree
 	if flag fetch; then
       flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-      sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
-      sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+      sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
+      sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
 
   if ! git_is_branch_merged_into "$PRODUCTION_BRANCH" "$BRANCH"; then
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -183,8 +183,8 @@ cmd_start() {
 	require_tag_absent "$RELEASES_PREFIX$REL_NAME"
 	if flag fetch; then
         flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
-        sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+        sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
+        sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
     require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
     require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
@@ -220,8 +220,8 @@ cmd_finish() {
 	require_clean_working_tree
 	if flag fetch; then
         flow_do "Fetching $ORIGIN" "" fetch -q "$ORIGIN"
-        sync_branch "$PRODUCTION_BRANCH" "nopush" || die "Unable to synchronize production" 
-        sync_branch "$DEVELOP_BRANCH" "nopush" || die "Unable to synchronize master" 
+        sync_branch "$PRODUCTION_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize production" 
+        sync_branch "$DEVELOP_BRANCH" "nopush" "--first-parent" || die "Unable to synchronize master" 
 	fi
 	
     require_branches_equal "$PRODUCTION_BRANCH" "$ORIGIN/$PRODUCTION_BRANCH"
